---

- name: Ensure dependencies are installed
  become: yes
  apt:
    name:
      - git
      - git-lfs
      - software-properties-common
      - python3
      - python3-venv
      - python3-pip
    state: present
    update_cache: yes
  tags:
    - setup

#- name: Create deploy user
#  user:
#    name: "{{ deploy_user }}"
#    groups: sudo
#    shell: /bin/bash
#    create_home: yes
#    state: present

#- name: Allow SSH for deploy user
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: '^AllowUsers'
#    line: "AllowUsers {{ deploy_user }} root"
#  notify: restart ssh
