---

- name: Create the application user
  become: yes

  ansible.builtin.user: name={{ gunicorn_user }} state=present

- name: Create the application group
  become: yes

  ansible.builtin.group: name={{ gunicorn_group }} system=yes state=present

- name: Add the application user to the application group
  become: yes

  ansible.builtin.user: name={{ gunicorn_user }} group={{ gunicorn_group }} state=present
