---

- ansible.builtin.import_tasks: create_users_and_groups.yml

- ansible.builtin.import_tasks: setup_git_repo.yml
  tags: deploy

- ansible.builtin.import_tasks: setup_virtualenv.yml
  tags: virtualenv

- ansible.builtin.import_tasks: setup_django_app.yml
  tags: deploy

- ansible.builtin.import_tasks: setup_systemd.yml
  tags: systemd
