version: "3.8"

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    # ports:
    # - 15672:15672
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  flower:
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672//
      - FLOWER_PORT=5555
      - FLOWER_PURGE_OFFLINE_WORKERS=10
    # ports:
    # - 5555:5555
    links:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  vod_ingest:
    image: gitlab.telekom.si:4567/vidra/vidra-kit
    build:
      context: .
      dockerfile: ./workflows/Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
